// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Toker is an autogenerated mock type for the Toker type
type Toker struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: userID, isAdmin
func (_m *Toker) CreateToken(userID string, isAdmin bool) (string, error) {
	ret := _m.Called(userID, isAdmin)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, bool) string); ok {
		r0 = rf(userID, isAdmin)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(userID, isAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewToker interface {
	mock.TestingT
	Cleanup(func())
}

// NewToker creates a new instance of Toker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewToker(t mockConstructorTestingTNewToker) *Toker {
	mock := &Toker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
