// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WhatsApper is an autogenerated mock type for the WhatsApper type
type WhatsApper struct {
	mock.Mock
}

// SendWhatsAppMessage provides a mock function with given fields: to, pin
func (_m *WhatsApper) SendWhatsAppMessage(to string, pin string) error {
	ret := _m.Called(to, pin)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(to, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWhatsApper interface {
	mock.TestingT
	Cleanup(func())
}

// NewWhatsApper creates a new instance of WhatsApper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWhatsApper(t mockConstructorTestingTNewWhatsApper) *WhatsApper {
	mock := &WhatsApper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
