// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fiufit/users/models"
	mock "github.com/stretchr/testify/mock"
)

// Notifications is an autogenerated mock type for the Notifications type
type Notifications struct {
	mock.Mock
}

// SendCertificationNotification provides a mock function with given fields: ctx, userID, certificationStatus
func (_m *Notifications) SendCertificationNotification(ctx context.Context, userID string, certificationStatus string) error {
	ret := _m.Called(ctx, userID, certificationStatus)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, certificationStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendFollowersNotification provides a mock function with given fields: ctx, follower, followed
func (_m *Notifications) SendFollowersNotification(ctx context.Context, follower models.User, followed models.User) error {
	ret := _m.Called(ctx, follower, followed)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User, models.User) error); ok {
		r0 = rf(ctx, follower, followed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewNotifications interface {
	mock.TestingT
	Cleanup(func())
}

// NewNotifications creates a new instance of Notifications. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNotifications(t mockConstructorTestingTNewNotifications) *Notifications {
	mock := &Notifications{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
